### ISSUE TITLE
CORS: no origin defined

### ISSUE THREAD

**Issue by pt232** [averywlittle/tweetsort#1]
Hey, 🤗

I stumbled across this app and I think it's really great!

But I noticed that you don't define an origin for the [cors](https://www.npmjs.com/package/cors) package. So anyone can make an API request to the Twitter API through your server.  

At the following point, it's best to set the `origin` property:

https://github.com/averywlittle/tweetsort/blob/57b6969a276b37c577ec889c02a38acb74b98a0b/server/app.js#L6

You can find the explanation in the [README](https://github.com/expressjs/cors).

Best regards! ✌

**Comment by averywlittle** [comment]
Hey Tobias!

Thanks for pointing this out! This code is an old, educational project, and is no longer deployed. Feel free to make a pull request if you'd like to change this!

Update: I wrote a little note in the readme to say this code is deprecated and for educational purposes only

**Comment by pt232** [comment]
My bad, I missed that!
